/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "ZPrimeMuonBkgPdfMBWZg.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(ZPrimeMuonBkgPdfMBWZg) 

 ZPrimeMuonBkgPdfMBWZg::ZPrimeMuonBkgPdfMBWZg(const char *name, const char *title, 
                        RooAbsReal& _mass,
                        RooAbsReal& _bkg_a,
                        RooAbsReal& _bkg_b,
                        RooAbsReal& _bkg_c,
                        RooAbsReal& _bkg_d
   ):
   RooAbsPdf(name,title), 
   mass("mass","mass",this,_mass),
   bkg_a(" bkg_a"," bkg_a",this,_bkg_a),
   bkg_b(" bkg_b"," bkg_b",this,_bkg_b),
   bkg_c(" bkg_c"," bkg_c",this,_bkg_c),
   bkg_d(" bkg_d"," bkg_d",this,_bkg_d)
 {
 }


 ZPrimeMuonBkgPdfMBWZg::ZPrimeMuonBkgPdfMBWZg(const ZPrimeMuonBkgPdfMBWZg& other, const char* name) :  
   RooAbsPdf(other,name), 
   mass("mass",this,other.mass),
   bkg_a("bkg_a",this,other.bkg_a),
   bkg_b("bkg_b",this,other.bkg_b),
   bkg_c("bkg_c",this,other.bkg_c),
   bkg_d("bkg_d",this,other.bkg_d)
 { 
 } 



 Double_t ZPrimeMuonBkgPdfMBWZg::evaluate() const 
 {
	if (mass < 91.1876) return 0;
	return bkg_a*TMath::Exp(bkg_b*mass)* ( bkg_c*(1./( pow((mass-91.1876),2.) + 2.4952*2.4952*0.25)) + (1.-bkg_c)*(1./pow(mass,bkg_d)) );
	//return TMath::Exp(bkg_b*mass)* ( bkg_c*(1./( pow((mass-91.1876),2.) + 2.4952*2.4952*0.25)) + (1.-bkg_c)*(1./pow(mass,bkg_d)) );
 }
