/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
o *****************************************************************************/

#ifndef ZPRIMEMUONBKGPDFMRBW
#define ZPRIMEMUONBKGPDFMRBW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeMuonBkgPdfMRBW : public RooAbsPdf {
public:
  ZPrimeMuonBkgPdfMRBW() {} ; 
  ZPrimeMuonBkgPdfMRBW(const char *name, const char *title,
              RooAbsReal& _mass,
              RooAbsReal& _bkg_a,
              RooAbsReal& _bkg_b,
              RooAbsReal& _bkg_c,
              RooAbsReal& _bkg_d
  );
  ZPrimeMuonBkgPdfMRBW(const ZPrimeMuonBkgPdfMRBW& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeMuonBkgPdfMRBW(*this,newname); }
  inline virtual ~ZPrimeMuonBkgPdfMRBW() { }

protected:

  RooRealProxy  mass;
  RooRealProxy  bkg_a;
  RooRealProxy  bkg_b;
  RooRealProxy  bkg_c;
  RooRealProxy  bkg_d;

  Double_t evaluate() const ;

private:
  ClassDef(ZPrimeMuonBkgPdfMRBW,1) // Your description goes here...
};

#endif
