/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
o *****************************************************************************/

#ifndef ZPRIMEMUONBKGPDFMBWZG
#define ZPRIMEMUONBKGPDFMBWZG

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeMuonBkgPdfMBWZg : public RooAbsPdf {
public:
  ZPrimeMuonBkgPdfMBWZg() {} ; 
  ZPrimeMuonBkgPdfMBWZg(const char *name, const char *title,
              RooAbsReal& _mass,
              RooAbsReal& _bkg_a,
              RooAbsReal& _bkg_b,
              RooAbsReal& _bkg_c,
              RooAbsReal& _bkg_d
  );
  ZPrimeMuonBkgPdfMBWZg(const ZPrimeMuonBkgPdfMBWZg& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeMuonBkgPdfMBWZg(*this,newname); }
  inline virtual ~ZPrimeMuonBkgPdfMBWZg() { }

protected:

  RooRealProxy  mass;
  RooRealProxy  bkg_a;
  RooRealProxy  bkg_b;
  RooRealProxy  bkg_c;
  RooRealProxy  bkg_d;

  Double_t evaluate() const ;

private:
  ClassDef(ZPrimeMuonBkgPdfMBWZg,1) // Your description goes here...
};

#endif
